- hosts: all
  become: yes
  vars: 
    base_locale: LANG=ko_KR.UTF-8
    base_timezone: Asia/Tokyo
  tasks:
    # 기본 서버 설정
    - name: 로케일 설정
      command: localectl set-locale {{ base_locale }}
    
    - name: 타임존 설정
      command: timedatectl set-timezone {{ base_timezone }}

    - name: 기본 패키지 설정
      yum:
        name: 
          - vim
          - git
          - ntp 
        state: present

    - name: ntpd 활성화
      service: 
        name: ntpd
        state: started
        enabled: yes

- import_playbook: web.yml
- import_playbook: db.yml
- import_playbook: deploy.yml