---
- name: find directory
  shell: 'find {{express_path}}'
  failed_when: False
  changed_when: False
  register: finding

- name: create directory
  file:
    path: '{{app_path}}'
    state: directory
  when: finding.rc == 1

- name: create express app
  shell: 'express {{express_path}}'
  failed_when: False
  changed_when: False
  when: finding.rc == 1

- name: install all dependancies
  npm: 
    path: '{{express_path}}'
