Vagrant.configure(2) do |config|
    config.ssh.insert_key = false
    config.vm.provider :virtualbox do |provider, override|
        provider.name = 'ansible.devops.node'
        provider.memory = 1024
    end

    config.vm.box = "ubuntu/trusty64"
    config.vm.hostname = 'ansible.devops.node'
    config.vm.network :forwarded_port, host: 8888, guest: 8888
    
    config.vm.synced_folder '.', '/vagrant', mount_options: ['dmode=777', 'fmode=666']
end