# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.ssh.insert_key = false
    config.vm.provider :virtualbox do |provider|
        provider.name = 'ansible.devops.node'
        provider.memory = 1024
    end

    config.vm.box = "ubuntu/trusty64"
    config.vm.hostname = 'ansible.devops'
    config.vm.network :forwarded_port, host: 8888, guest: 8888
    config.vm.network :private_network, ip: '192.168.11.109'
    
    config.vm.synced_folder '.', '/vagrant', mount_options: ['dmode=777', 'fmode=666']
end